import type { QuickWinDefinition } from "./types";

export const QUICK_WIN_DEFINITIONS: QuickWinDefinition[] = [
  {
    winType: "missing_seo",
    category: "seo",
    factTypes: ["MissingSEO"],
    title: (count) => `${count} product${count === 1 ? "" : "s"} missing SEO`,
    description: "Products lack SEO titles needed for search visibility.",
    effort: 1,
    impactWeight: 0.75,
    urgencyBoost: 10,
  },
  {
    winType: "missing_meta_description",
    category: "seo",
    factTypes: ["MissingMetaDescription"],
    title: (count) => `${count} product${count === 1 ? "" : "s"} missing meta descriptions`,
    description: "Meta descriptions improve click-through from search results.",
    effort: 1,
    impactWeight: 0.65,
    urgencyBoost: 8,
  },
  {
    winType: "missing_alt_text",
    category: "seo",
    factTypes: ["MissingAltText"],
    title: (count) => `${count} product${count === 1 ? "" : "s"} missing alt text`,
    description: "Image alt text improves accessibility and image search.",
    effort: 1,
    impactWeight: 0.55,
    urgencyBoost: 6,
  },
  {
    winType: "no_description",
    category: "seo",
    factTypes: ["NoDescription"],
    title: (count) => `${count} product${count === 1 ? "" : "s"} without descriptions`,
    description: "Product descriptions help conversion and SEO relevance.",
    effort: 2,
    impactWeight: 0.6,
    urgencyBoost: 7,
  },
  {
    winType: "no_images",
    category: "catalog",
    factTypes: ["LowMediaCoverage"],
    title: (count) => `${count} product${count === 1 ? "" : "s"} with low media coverage`,
    description: "Products need stronger visual coverage to convert.",
    effort: 2,
    impactWeight: 0.7,
    urgencyBoost: 9,
  },
  {
    winType: "low_stock",
    category: "inventory",
    factTypes: ["InventoryLow", "InventoryCritical"],
    title: (count) => `${count} inventory risk${count === 1 ? "" : "s"}`,
    description: "Variants are running low and may stock out soon.",
    effort: 2,
    impactWeight: 0.9,
    urgencyBoost: 25,
  },
  {
    winType: "out_of_stock",
    category: "inventory",
    factTypes: ["OutOfStock"],
    title: (count) => `${count} out-of-stock variant${count === 1 ? "" : "s"}`,
    description: "Out-of-stock products cannot generate revenue.",
    effort: 2,
    impactWeight: 0.95,
    urgencyBoost: 30,
  },
  {
    winType: "overstock",
    category: "inventory",
    factTypes: ["HighInventory"],
    title: (count) => `${count} overstock signal${count === 1 ? "" : "s"}`,
    description: "Excess inventory ties up capital and storage.",
    effort: 2,
    impactWeight: 0.6,
    urgencyBoost: 12,
  },
  {
    winType: "inventory_risk",
    category: "inventory",
    factTypes: ["InventoryLow", "InventoryCritical", "OutOfStock"],
    title: (count) => `${count} combined inventory risk${count === 1 ? "" : "s"}`,
    description: "Aggregate inventory risks across low stock and out-of-stock signals.",
    effort: 2,
    impactWeight: 0.92,
    urgencyBoost: 28,
  },
  {
    winType: "never_sold_product",
    category: "catalog",
    factTypes: ["NeverSold"],
    title: (count) => `${count} never-sold product${count === 1 ? "" : "s"}`,
    description: "Products with zero sales may need repricing or promotion.",
    effort: 2,
    impactWeight: 0.7,
    urgencyBoost: 10,
  },
  {
    winType: "dead_product",
    category: "catalog",
    factTypes: ["NeverSold", "InactiveProduct", "Discontinued"],
    title: (count) => `${count} dead or inactive product${count === 1 ? "" : "s"}`,
    description: "Stale catalog items dilute merchandising focus.",
    effort: 2,
    impactWeight: 0.68,
    urgencyBoost: 8,
  },
  {
    winType: "slow_moving_product",
    category: "catalog",
    factTypes: ["NeverSold", "HighInventory"],
    title: (count) => `${count} slow-moving product${count === 1 ? "" : "s"}`,
    description: "Products with weak sales velocity and excess inventory.",
    effort: 3,
    impactWeight: 0.62,
    urgencyBoost: 11,
  },
  {
    winType: "inactive_product",
    category: "catalog",
    factTypes: ["InactiveProduct"],
    title: (count) => `${count} inactive product${count === 1 ? "" : "s"}`,
    description: "Inactive products may be cluttering the catalog.",
    effort: 1,
    impactWeight: 0.5,
    urgencyBoost: 5,
  },
  {
    winType: "draft_too_long",
    category: "catalog",
    factTypes: ["DraftTooLong"],
    title: (count) => `${count} draft product${count === 1 ? "" : "s"} waiting too long`,
    description: "Long-running drafts delay revenue from new products.",
    effort: 1,
    impactWeight: 0.58,
    urgencyBoost: 9,
  },
  {
    winType: "bundle_candidate",
    category: "catalog",
    factTypes: ["BundleCandidateSeed"],
    title: (count) => `${count} bundle candidate${count === 1 ? "" : "s"}`,
    description: "Products that could be bundled to increase average order value.",
    effort: 3,
    impactWeight: 0.8,
    urgencyBoost: 14,
  },
  {
    winType: "pricing_outlier",
    category: "pricing",
    factTypes: ["PriceAboveCategoryAverage", "PriceChanged"],
    title: (count) => `${count} pricing opportunit${count === 1 ? "y" : "ies"}`,
    description: "Pricing anomalies detected against category baselines.",
    effort: 2,
    impactWeight: 0.78,
    urgencyBoost: 13,
  },
  {
    winType: "margin_risk",
    category: "pricing",
    factTypes: ["MarginRiskCandidate"],
    title: (count) => `${count} margin risk candidate${count === 1 ? "" : "s"}`,
    description: "Products with margin pressure based on cost and price signals.",
    effort: 3,
    impactWeight: 0.85,
    urgencyBoost: 16,
  },
  {
    winType: "collection_issue",
    category: "collections",
    factTypes: ["OrphanCollection", "SingleProductCollection"],
    title: (count) => `${count} collection issue${count === 1 ? "" : "s"}`,
    description: "Collections need merchandising attention.",
    effort: 2,
    impactWeight: 0.55,
    urgencyBoost: 7,
  },
  {
    winType: "high_refund_risk",
    category: "operations",
    factTypes: ["RefundRiskSeed"],
    title: (count) => `${count} high refund risk signal${count === 1 ? "" : "s"}`,
    description: "Operational refund risk indicators detected from order history.",
    effort: 3,
    impactWeight: 0.88,
    urgencyBoost: 20,
  },
];

export const TRIAL_CATEGORY_PRIORITY = [
  "inventory",
  "pricing",
  "seo",
  "catalog",
  "collections",
  "operations",
] as const;

export const DEFAULT_AOV_FALLBACK = 75;

export const REVENUE_OPPORTUNITY_MULTIPLIERS: Record<string, number> = {
  inventory: 1.2,
  pricing: 1.0,
  seo: 0.6,
  catalog: 0.5,
  collections: 0.4,
  operations: 0.9,
};
