import { createElement } from "react";
import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import { createMemoryRouter, RouterProvider } from "react-router";

import { CommandCenter } from "../CommandCenter";
import type { CommandCenterData } from "../../../services/command-center.server";

const commandCenter = {
  header: {
    merchantName: "John",
    greeting: "Good morning",
    storeHealth: 86,
    criticalIssues: 2,
    opportunities: 4,
    potentialRevenue: 43000,
  },
  briefing: {
    headline: "Your AI COO has analyzed your store.",
    paragraphs: ["Your AI COO analyzed 184 products using persisted Product Intelligence results."],
  },
  activityFeed: [
    {
      id: "run-batch:2026-06-20",
      tone: "success",
      title: "Product Intelligence completed",
      detail: "Analyzed 184 products",
      metrics: [
        { label: "Duration", value: "12 sec" },
        { label: "Recommendations", value: "8" },
        { label: "Estimated Revenue", value: "+$18,200" },
      ],
      at: "2026-06-20T09:12:00.000Z",
    },
  ],
  agents: [
    {
      id: "product_intelligence",
      name: "Product Intelligence",
      status: "healthy",
      description: "Analyzes product performance and generates merchant-ready recommendations.",
      lastRunAt: "2026-06-20T09:12:00.000Z",
      durationMs: 4200,
      recommendationCount: 8,
      costUsd: 1.2,
      latencyMs: 4200,
      healthLabel: "Healthy",
    },
  ],
  executive: {
    summaryCards: {
      storeHealth: 86,
      revenueHealth: 82,
      inventoryHealth: 74,
      growthScore: 68,
      aiConfidence: 0.9,
      openRecommendations: 1,
      highPriorityTasks: 1,
    },
    briefing: {
      greeting: "Good morning.",
      storeHealth: 86,
      summaryLines: [],
      estimatedOpportunity: 43000,
      highestPriorities: [],
    },
    groupedRecommendations: {
      "Critical Risks": [],
      "Revenue Opportunities": [],
      "Quick Wins": [],
      "Operational Improvements": [],
      "Long-Term Strategy": [],
    },
    productSpotlight: null,
    analytics: {
      revenueTrend: [{ label: "Jun 01", value: 100 }],
      inventoryTrend: [{ label: "Jun 01", value: 50 }],
      healthScoreHistory: [],
      recommendationImpact: [],
      topProducts: [],
      bottomProducts: [],
      velocityTrend: [],
      refundTrend: [],
      inventoryAge: [],
      healthDistribution: [],
      recommendationCompletionRate: 0,
      inventoryHealthHistory: [],
      deadStockCount: [],
      stockCoverageTrend: [],
      reorderTimeline: [],
      inventoryRiskDistribution: [],
      topBundleOpportunities: [],
      bundleSuccessRate: [],
      potentialInventoryReduction: [],
      potentialAttachRate: [],
      bundleHealth: [],
      abcDistribution: [],
      weeksOfCover: [],
      capitalLocked: [],
      inventoryTimeline: [],
      storeAuditHealth: [],
      homepageScore: [],
      seoScoreHistory: [],
      accessibilityScoreHistory: [],
      performanceScoreHistory: [],
      themeScoreHistory: [],
      conversionScoreHistory: [],
      mobileScoreHistory: [],
      storeAuditIssueDistribution: [],
      storeAuditRecommendationTrend: [],
      trendHealth: [],
      emergingProductsTrend: [],
      decliningProductsTrend: [],
      momentumTrend: [],
      growthVsDeclineTrend: [],
      trendRevenueTrend: [],
      trendVelocityTrend: [],
      seasonalityTrend: [],
      categoryTrendChart: [],
      trendTimeline: [],
      seoIntelligenceHealthHistory: [],
      seoVisibilityTrend: [],
      seoCtrTrend: [],
      seoOrganicOpportunity: [],
      seoCoreWebVitalsTrend: [],
      seoTechnicalRadar: [],
      seoIssueDistribution: [],
      seoKeywordDistribution: [],
      seoPositionTrend: [],
      seoIndexCoverage: [],
      seoContentQuality: [],
      seoHealthTimeline: [],
      pricingHealthHistory: [],
      marginTrend: [],
      revenueVsProfit: [],
      discountTrend: [],
      priceDistribution: [],
      pricingRisk: [],
      pricingOpportunityFunnel: [],
      marginDistribution: [],
      discountDependenceTrend: [],
      pricingTimeline: [],
    },
    storeAuditPanel: {
      overallAuditScore: 74,
      auditHealth: 74,
      criticalIssues: 0,
      seoHealth: 76,
      performanceHealth: 72,
      accessibilityHealth: 71,
      auditHistory: [],
      auditTimeline: [],
      trendChart: [],
    },
    seoIntelligencePanel: {
      seoHealth: 78,
      seoTrend: [{ label: "Run 1", value: 78 }],
      organicOpportunity: 42,
      searchVisibility: 65,
      coreWebVitals: 74,
      technicalSeo: 72,
      contentQuality: 68,
      indexCoverage: 80,
      structuredData: 85,
      quickWins: [{ label: "Improve meta titles", value: 5 }],
      opportunityTimeline: [{ label: "SEO Health", value: 78 }],
      seoHistory: [{ label: "Run 1", value: 78 }],
    },
    pricingIntelligencePanel: {
      pricingHealth: 0,
      marginPercent: 0,
      profitOpportunity: 0,
      revenueOpportunity: 0,
      averageDiscountPercent: 0,
      discountDependence: 0,
      pricingHealthTrend: [],
      marginTrend: [],
      revenueVsProfit: [],
      discountTrend: [],
      priceDistribution: [],
      pricingRisk: [],
      opportunityFunnel: [],
      marginDistribution: [],
      discountDependenceTrend: [],
      pricingTimeline: [],
      criticalPricingRisks: [],
    },
    growthIntelligencePanel: {
      growthScore: 0,
      monthlyRevenueOpportunity: 0,
      aovOpportunity: 0,
      repeatPurchaseOpportunity: 0,
      expansionReadiness: 0,
      growthTrend: [],
      opportunityFunnel: [],
      growthCategories: [],
      revenueLiftForecast: [],
      growthRoi: [],
      campaignTimeline: [],
      collectionPerformance: [],
      growthCapacity: [],
      revenueSources: [],
      priorityDistribution: [],
      criticalGrowthRisks: [],
    },
    executiveCooPanel: {
      todaysPriority: null,
      businessHealth: 0,
      executiveConfidence: 0,
      merchantCapacity: 0,
      businessMomentum: 0,
      criticalPathLength: 0,
      executionTimeline: [],
      priorityDistribution: [],
      businessHealthTrend: [],
      capacityUsage: [],
      opportunityCostChart: [],
      dependencyGraph: [],
      executionFunnel: [],
      businessMomentumChart: [],
      criticalPathChart: [],
      blockedTasksChart: [],
    },
    executiveDecisions: [],
    collaborationSummary: null,
    collaborationCharts: {
      consensusGauge: [],
      agentInfluenceRadar: [],
      dependencyGraph: [],
      priorityMatrixImpact: [],
      priorityMatrixEffort: [],
      conflictHeatmap: [],
      recommendationSankey: [],
      decisionTimeline: [],
      roiWaterfall: [],
      healthWheel: [],
      confidenceDistribution: [],
    },
    timeline: [],
    tasks: [],
    recommendations: [
      {
        stableId: "stable-1",
        id: "inventory-replenishment-plan",
        subjectKey: "product:product-1",
        productId: "product-1",
        productTitle: "Protein Powder",
        title: "Increase inventory for Protein Powder",
        reason: "Sales velocity increased while inventory decreased to six days.",
        category: "Inventory",
        group: "Critical Risks",
        priority: 1,
        priorityScore: 91,
        confidence: 0.96,
        difficulty: "Easy",
        evidence: ["30 day sales +38%"],
        estimatedImpact: {
          revenueRecovered: 42000,
          revenueOpportunity: null,
          ordersProtected: null,
          inventoryDaysSaved: null,
          inventoryCostSaved: null,
          estimatedLostSales: null,
          marginImprovement: null,
        },
        merchantAction: ["Order 300 additional units"],
        tasks: ["Increase inventory"],
        timeline: { detected: "2026-06-20T08:00:00.000Z", created: "2026-06-20T08:00:00.000Z" },
        status: "open",
        verification: {},
        expectedResult: "Restore inventory coverage",
        potentialRisk: "Capital tied up if demand softens",
        estimatedTime: "1-2 weeks",
        businessImpact: "Protect revenue during sustained demand",
        lastSeenAt: "2026-06-20T08:00:00.000Z",
        updatedAt: "2026-06-20T08:00:00.000Z",
      },
    ],
    storeHealthScore: {
      score: 86,
      grade: "B",
      productsScore: 20,
      inventoryScore: 20,
      ordersScore: 40,
      issues: [],
    },
    metrics: {
      products: 10,
      activeProducts: 10,
      orders: 100,
      grossRevenue: 1000,
      averageOrderValue: 10,
      lowStockProducts: 1,
      outOfStockProducts: 0,
      inventoryUnits: 100,
    },
    currency: "USD",
    lastUpdatedAt: "2026-06-20T09:12:00.000Z",
  },
  healthRing: {
    score: 86,
    segments: [
      { label: "Inventory", value: 74 },
      { label: "Revenue", value: 82 },
      { label: "Conversion", value: 68 },
      { label: "SEO", value: 78 },
      { label: "Pricing", value: 74 },
    ],
  },
  pipeline: {
    critical: [],
    high: [],
    medium: [],
    low: [],
  },
  charts: {
    revenueTrend: [{ label: "Jun 01", value: 100 }],
    revenueVsRefunds: [{ label: "Jun 01", revenue: 100, refunds: 5 }],
    topProducts: [],
    bottomProducts: [],
    healthScoreHistory: [],
    recommendationCategories: [],
    inventoryAge: [],
    recommendationStatus: [],
    revenueOpportunityFunnel: [],
    storeHealthBreakdown: [],
  },
  aiTimeline: [
    {
      id: "timeline-run:run-1",
      timeLabel: "09:12",
      title: "Product Intelligence",
      detail: "Completed",
      tone: "success",
      at: "2026-06-20T09:12:00.000Z",
    },
  ],
  costWidget: {
    creditsUsed: 12,
    remainingCredits: 88,
    creditLimit: 100,
    estimatedValueGenerated: 43000,
  },
  inventoryIntelligence: {
    inventoryHealth: 78,
    openRecommendations: 1,
    stockoutAlerts: 2,
    deadStockAlerts: 1,
    recentExecutions: 3,
    capitalLocked: 348,
    averageWeeksOfCover: 1.7,
    fastMovers: 1,
    slowMovers: 0,
    inventoryAlerts: [
      { label: "Stockout", value: 2 },
      { label: "Dead Stock", value: 1 },
    ],
    recommendationGroups: [{ label: "Immediate Reorders", value: 1 }],
    opportunityPipeline: [{ label: "Critical", value: 1 }],
    inventoryTrend: [{ label: "Health", value: 78 }],
  },
  bundleDiscovery: {
    bundleHealth: 82,
    openRecommendations: 1,
    topOpportunities: 2,
    potentialInventoryReduction: 12,
    potentialAttachRate: 0.41,
    recentExecutions: 2,
    recommendationGroups: [{ label: "Top Bundle Opportunities", value: 1 }],
  },
  storeAudit: {
    overallAuditScore: 74,
    storeHealth: 74,
    homepageScore: 78,
    seoScore: 76,
    accessibilityScore: 71,
    performanceScore: 72,
    conversionScore: 69,
    mobileScore: 73,
    themeScore: 70,
    openRecommendations: 1,
    criticalIssues: 1,
    recentExecutions: 1,
    recommendationGroups: [{ label: "Quick Wins", value: 1 }],
    issueDistribution: [{ label: "SEO", value: 1 }],
    topFixes: [{ label: "Add social proof", value: 5 }],
    quickWins: [{ label: "Add social proof", value: 5 }],
    criticalIssueFeed: [{ id: "audit-1", title: "Missing alt text", category: "Images" }],
    healthTrend: [{ label: "Health", value: 74 }],
    categoryBreakdown: [{ label: "SEO", value: 1 }],
    seoWidgets: [{ label: "SEO Score", value: 76 }],
    accessibilityWidgets: [{ label: "Accessibility Score", value: 71 }],
    performanceWidgets: [{ label: "Performance Score", value: 72 }],
    auditTimeline: [{ label: "Health", value: 74 }],
    opportunityPipeline: [{ label: "High", value: 1 }],
  },
  trendIntelligence: {
    trendHealth: 72,
    trendDirection: "mixed",
    openRecommendations: 1,
    emergingCount: 1,
    decliningCount: 1,
    recentExecutions: 1,
    growthAlerts: 1,
    declineAlerts: 1,
    recommendationGroups: [{ label: "Emerging Opportunities", value: 1 }],
    momentumCharts: [{ label: "Blue Hoodie", value: 72 }],
    emergingOpportunities: [{ label: "Blue Hoodie", value: 35 }],
    categoryOpportunities: [{ label: "Blue", value: 25 }],
    trendTimeline: [{ label: "Health", value: 72 }],
    opportunityPipeline: [{ label: "Emerging", value: 1 }],
  },
  seoIntelligence: {
    seoHealth: 78,
    organicOpportunity: 42,
    searchVisibility: 65,
    coreWebVitals: 74,
    technicalSeo: 72,
    contentQuality: 68,
    openRecommendations: 1,
    criticalIssues: 1,
    recentExecutions: 1,
    recommendationGroups: [{ label: "Quick Wins", value: 1 }],
    seoTimeline: [{ label: "SEO Health", value: 78 }],
    organicGrowth: [{ label: "Traffic", value: 120 }],
    criticalSeoFeed: [{ id: "seo-1", title: "Improve meta titles", category: "Metadata" }],
    quickWins: [{ label: "Improve meta titles", value: 5 }],
    trendHistory: [{ label: "Health", value: 78 }],
    issueDistribution: [{ label: "Metadata", value: 1 }],
    opportunityPipeline: [{ label: "High", value: 1 }],
  },
  pricingIntelligence: {
    pricingHealth: 74,
    marginPercent: 38,
    profitOpportunity: 12500,
    revenueOpportunity: 18200,
    openRecommendations: 1,
    criticalPricingRisks: 1,
    recentExecutions: 1,
    recommendationGroups: [{ label: "Margin Protection", value: 1 }],
    pricingTimeline: [
      { label: "Health", value: 74 },
      { label: "Revenue", value: 18200 },
      { label: "Profit", value: 12500 },
    ],
    marginTrend: [
      { label: "Margin", value: 38 },
      { label: "Target", value: 40 },
    ],
    criticalPricingFeed: [{ id: "pricing-1", title: "Raise Protein Powder price", category: "Margin Protection" }],
    opportunityPipeline: [{ label: "Critical", value: 1 }],
  },
  growthIntelligence: {
    growthScore: 72,
    monthlyRevenueOpportunity: 18200,
    aovOpportunity: 68,
    repeatPurchaseOpportunity: 24,
    expansionReadiness: 58,
    openRecommendations: 1,
    criticalGrowthRisks: 1,
    recentExecutions: 1,
    recommendationGroups: [{ label: "AOV Growth", value: 1 }],
    campaignTimeline: [
      { label: "Growth", value: 72 },
      { label: "Revenue", value: 18200 },
      { label: "AOV", value: 68 },
    ],
    growthTrend: [
      { label: "Growth", value: 72 },
      { label: "Revenue Rate", value: 8 },
    ],
    criticalGrowthFeed: [{ id: "growth-1", title: "Launch upsell campaign", category: "Upsell" }],
    opportunityPipeline: [{ label: "High", value: 1 }],
  },
  executiveCoo: {
    todaysPriority: "Replenish Protein Powder before stockout",
    businessHealth: 72,
    executiveConfidence: 86,
    merchantCapacity: 70,
    businessMomentum: 68,
    criticalPathLength: 1,
    openPriorities: 2,
    blockedTasks: 1,
    recentExecutions: 1,
    focusAreaGroups: [{ label: "Inventory", value: 1 }],
    executionTimeline: [{ label: "Run 1", value: 72 }],
    criticalPriorityFeed: [
      { id: "executive-1", title: "Replenish Protein Powder before stockout", category: "Inventory" },
    ],
    opportunityPipeline: [{ label: "Critical", value: 1 }],
    businessHealthTrend: [{ label: "Run 1", value: 72 }],
    capacityUsage: [{ label: "Capacity", value: 70 }],
    blockedTasksChart: [{ label: "Replenish Protein", value: 5 }],
  },
  executiveDecisions: {
    topDecision: null,
    consensusScore: 0,
    conflictCount: 0,
    dependencyCount: 0,
    topRisk: null,
    topOpportunity: null,
    decisions: [],
    charts: {
      consensusGauge: [],
      agentInfluenceRadar: [],
      dependencyGraph: [],
      priorityMatrixImpact: [],
      priorityMatrixEffort: [],
      conflictHeatmap: [],
      recommendationSankey: [],
      decisionTimeline: [],
      roiWaterfall: [],
      healthWheel: [],
      confidenceDistribution: [],
    },
  },
  currency: "USD",
} satisfies CommandCenterData;

describe("Command center components", () => {
  it("renders briefing, activity feed, agents, and recommendation actions", () => {
    const router = createMemoryRouter(
      [
        {
          path: "/",
          element: createElement(CommandCenter, {
            data: commandCenter,
            onOpenRecommendation: () => undefined,
          }),
        },
      ],
      { initialEntries: ["/"] },
    );

    const html = renderToString(createElement(RouterProvider, { router }));

    expect(html).toContain("Good morning");
    expect(html).toContain("John");
    expect(html).toContain("AI Activity Feed");
    expect(html).toContain("Product Intelligence completed");
    expect(html).toContain("Active AI Agents");
    expect(html).toContain("Increase inventory for Protein Powder");
    expect(html).toContain("Implement");
    expect(html).toContain("Inventory Intelligence");
    expect(html).toContain("Bundle Intelligence");
    expect(html).toContain("Store Audit Intelligence");
    expect(html).toContain("Quick Wins");
  });
});
