import { createElement } from "react";
import { describe, expect, it } from "vitest";
import { renderToString } from "react-dom/server";
import { createMemoryRouter, RouterProvider } from "react-router";

import { ExecutiveDashboard } from "../ExecutiveDashboard";
import type { ExecutiveDashboardData } from "../../../services/executive-dashboard.server";

const dashboard = {
  summaryCards: {
    storeHealth: 91,
    revenueHealth: 82,
    inventoryHealth: 74,
    growthScore: 68,
    aiConfidence: 0.92,
    openRecommendations: 1,
    highPriorityTasks: 1,
  },
  briefing: {
    greeting: "Good morning.",
    storeHealth: 91,
    summaryLines: ["Store health is 91 / 100."],
    estimatedOpportunity: 82400,
    highestPriorities: ["Increase inventory for Protein Powder"],
  },
  groupedRecommendations: {
    "Critical Risks": [
      {
        stableId: "stable-1",
        id: "inventory-replenishment-plan",
        subjectKey: "product:product-1",
        productId: "product-1",
        productTitle: "Protein Powder",
        title: "Increase inventory for Protein Powder",
        reason: "Sales velocity increased while inventory decreased to six days.",
        category: "Inventory",
        group: "Critical Risks",
        priority: 1,
        priorityScore: 91,
        confidence: 0.96,
        difficulty: "Easy",
        evidence: ["30 day sales +38%"],
        estimatedImpact: {
          revenueRecovered: 42000,
          revenueOpportunity: null,
          ordersProtected: null,
          inventoryDaysSaved: null,
          inventoryCostSaved: null,
          estimatedLostSales: null,
          marginImprovement: null,
        },
        merchantAction: ["Order 300 additional units"],
        tasks: ["Increase inventory"],
        timeline: { detected: "2026-06-20T08:00:00.000Z", created: "2026-06-20T08:00:00.000Z" },
        status: "open",
        verification: {},
        expectedResult: "Restore inventory coverage",
        potentialRisk: "Capital tied up if demand softens",
        estimatedTime: "1-2 weeks",
        businessImpact: "Protect revenue during sustained demand",
        lastSeenAt: "2026-06-20T08:00:00.000Z",
        updatedAt: "2026-06-20T08:00:00.000Z",
      },
    ],
    "Revenue Opportunities": [],
    "Quick Wins": [],
    "Operational Improvements": [],
    "Long-Term Strategy": [],
  },
  productSpotlight: null,
  analytics: {
    revenueTrend: [{ label: "Jun 01", value: 100 }],
    inventoryTrend: [],
    healthScoreHistory: [],
    recommendationImpact: [],
    topProducts: [],
    bottomProducts: [],
    velocityTrend: [],
    refundTrend: [],
    inventoryAge: [],
    healthDistribution: [],
    recommendationCompletionRate: 0,
    inventoryHealthHistory: [],
    deadStockCount: [],
    stockCoverageTrend: [],
    reorderTimeline: [],
    inventoryRiskDistribution: [],
    topBundleOpportunities: [],
    bundleSuccessRate: [],
    potentialInventoryReduction: [],
    potentialAttachRate: [],
    bundleHealth: [],
    abcDistribution: [],
    weeksOfCover: [],
    capitalLocked: [],
    inventoryTimeline: [],
    storeAuditHealth: [],
    homepageScore: [],
    seoScoreHistory: [],
    accessibilityScoreHistory: [],
    performanceScoreHistory: [],
    themeScoreHistory: [],
    conversionScoreHistory: [],
    mobileScoreHistory: [],
    storeAuditIssueDistribution: [],
    storeAuditRecommendationTrend: [],
    trendHealth: [],
    emergingProductsTrend: [],
    decliningProductsTrend: [],
    momentumTrend: [],
    growthVsDeclineTrend: [],
    trendRevenueTrend: [],
    trendVelocityTrend: [],
    seasonalityTrend: [],
    categoryTrendChart: [],
    trendTimeline: [],
    seoIntelligenceHealthHistory: [],
    seoVisibilityTrend: [],
    seoCtrTrend: [],
    seoOrganicOpportunity: [],
    seoCoreWebVitalsTrend: [],
    seoTechnicalRadar: [],
    seoIssueDistribution: [],
    seoKeywordDistribution: [],
    seoPositionTrend: [],
    seoIndexCoverage: [],
    seoContentQuality: [],
    seoHealthTimeline: [],
    pricingHealthHistory: [],
    marginTrend: [],
    revenueVsProfit: [],
    discountTrend: [],
    priceDistribution: [],
    pricingRisk: [],
    pricingOpportunityFunnel: [],
    marginDistribution: [],
    discountDependenceTrend: [],
    pricingTimeline: [],
  },
  storeAuditPanel: {
    overallAuditScore: 74,
    auditHealth: 74,
    criticalIssues: 1,
    seoHealth: 76,
    performanceHealth: 72,
    accessibilityHealth: 71,
    auditHistory: [{ label: "Run 1", value: 74 }],
    auditTimeline: [
      { label: "Health", value: 74 },
      { label: "SEO", value: 76 },
    ],
    trendChart: [{ label: "Run 1", value: 74 }],
  },
  seoIntelligencePanel: {
    seoHealth: 78,
    seoTrend: [{ label: "Run 1", value: 78 }],
    organicOpportunity: 42,
    searchVisibility: 65,
    coreWebVitals: 74,
    technicalSeo: 72,
    contentQuality: 68,
    indexCoverage: 80,
    structuredData: 85,
    quickWins: [{ label: "Improve meta titles", value: 5 }],
    opportunityTimeline: [
      { label: "SEO Health", value: 78 },
      { label: "Traffic", value: 120 },
    ],
    seoHistory: [{ label: "Run 1", value: 78 }],
  },
  pricingIntelligencePanel: {
    pricingHealth: 74,
    marginPercent: 38,
    profitOpportunity: 12500,
    revenueOpportunity: 18200,
    averageDiscountPercent: 12,
    discountDependence: 28,
    pricingHealthTrend: [{ label: "Run 1", value: 74 }],
    marginTrend: [{ label: "Run 1", value: 38 }],
    revenueVsProfit: [
      { label: "Revenue", value: 42000 },
      { label: "Profit", value: 15960 },
    ],
    discountTrend: [{ label: "Run 1", value: 12 }],
    priceDistribution: [
      { label: "Low", value: 0 },
      { label: "Aligned", value: 1 },
    ],
    pricingRisk: [
      { label: "Revenue", value: 22 },
      { label: "Profit", value: 18 },
      { label: "Inventory", value: 14 },
    ],
    opportunityFunnel: [
      { label: "Revenue", value: 18200 },
      { label: "Profit", value: 12500 },
      { label: "Premium", value: 8 },
    ],
    marginDistribution: [
      { label: "Margin", value: 38 },
      { label: "Target", value: 40 },
    ],
    discountDependenceTrend: [{ label: "Run 1", value: 28 }],
    pricingTimeline: [
      { label: "Health", value: 74 },
      { label: "Revenue", value: 18200 },
      { label: "Profit", value: 12500 },
    ],
    criticalPricingRisks: [{ label: "Raise Protein Powder", value: 5 }],
  },
  growthIntelligencePanel: {
    growthScore: 72,
    monthlyRevenueOpportunity: 18200,
    aovOpportunity: 68,
    repeatPurchaseOpportunity: 24,
    expansionReadiness: 58,
    growthTrend: [{ label: "Run 1", value: 72 }],
    opportunityFunnel: [
      { label: "Revenue", value: 18200 },
      { label: "AOV", value: 68 },
      { label: "Upsell", value: 62 },
    ],
    growthCategories: [
      { label: "Upsell", value: 62 },
      { label: "Cross-sell", value: 55 },
      { label: "Retention", value: 58 },
    ],
    revenueLiftForecast: [{ label: "Run 1", value: 7 }],
    growthRoi: [{ label: "Run 1", value: 70 }],
    campaignTimeline: [
      { label: "Growth", value: 72 },
      { label: "Revenue", value: 18200 },
      { label: "AOV", value: 68 },
    ],
    collectionPerformance: [
      { label: "Collections", value: 64 },
      { label: "Merchandising", value: 60 },
    ],
    growthCapacity: [
      { label: "Capacity", value: 70 },
      { label: "Campaign Ready", value: 58 },
    ],
    revenueSources: [
      { label: "Revenue 30d", value: 12500 },
      { label: "Revenue 90d", value: 34200 },
    ],
    priorityDistribution: [
      { label: "Upsell", value: 62 },
      { label: "Retention", value: 58 },
      { label: "AOV", value: 62 },
    ],
    criticalGrowthRisks: [{ label: "Launch upsell", value: 5 }],
  },
  executiveCooPanel: {
    todaysPriority: "Replenish Protein Powder before stockout",
    businessHealth: 72,
    executiveConfidence: 86,
    merchantCapacity: 70,
    businessMomentum: 68,
    criticalPathLength: 1,
    executionTimeline: [{ label: "Run 1", value: 72 }],
    priorityDistribution: [{ label: "Inventory", value: 1 }],
    businessHealthTrend: [{ label: "Run 1", value: 72 }],
    capacityUsage: [
      { label: "Capacity", value: 70 },
      { label: "Open Priorities", value: 2 },
    ],
    opportunityCostChart: [
      { label: "Revenue", value: 18200 },
      { label: "Inventory Risk", value: 42 },
    ],
    dependencyGraph: [{ label: "Replenish Protein", value: 1 }],
    executionFunnel: [
      { label: "Critical", value: 1 },
      { label: "High", value: 1 },
      { label: "Medium", value: 0 },
      { label: "Low", value: 0 },
    ],
    businessMomentumChart: [{ label: "Run 1", value: 72 }],
    criticalPathChart: [{ label: "Replenish Protein", value: 5 }],
    blockedTasksChart: [{ label: "Replenish Protein", value: 5 }],
  },
  executiveDecisions: [],
  collaborationSummary: null,
  collaborationCharts: {
    consensusGauge: [],
    agentInfluenceRadar: [],
    dependencyGraph: [],
    priorityMatrixImpact: [],
    priorityMatrixEffort: [],
    conflictHeatmap: [],
    recommendationSankey: [],
    decisionTimeline: [],
    roiWaterfall: [],
    healthWheel: [],
    confidenceDistribution: [],
  },
  timeline: [
    {
      id: "stable-1:detected",
      stableId: "stable-1",
      recommendationId: "inventory-replenishment-plan",
      title: "Increase inventory for Protein Powder",
      type: "detected",
      message: "AI detected an issue",
      at: "2026-06-20T08:00:00.000Z",
    },
  ],
  tasks: [
    {
      id: "stable-1:0",
      title: "Increase inventory",
      priority: 1,
      estimatedImpact: 42000,
      difficulty: "Easy",
      relatedRecommendationId: "inventory-replenishment-plan",
      relatedRecommendationTitle: "Increase inventory for Protein Powder",
      stableId: "stable-1",
      subjectKey: "product:product-1",
    },
  ],
  recommendations: [],
  storeHealthScore: {
    score: 91,
    grade: "A",
    productsScore: 20,
    inventoryScore: 20,
    ordersScore: 40,
    issues: [],
  },
  metrics: {
    products: 10,
    activeProducts: 10,
    orders: 100,
    grossRevenue: 1000,
    averageOrderValue: 10,
    lowStockProducts: 1,
    outOfStockProducts: 0,
    inventoryUnits: 100,
  },
  currency: "USD",
  lastUpdatedAt: "2026-06-20T08:00:00.000Z",
} satisfies ExecutiveDashboardData;

describe("Executive dashboard components", () => {
  it("renders recommendation, task, and briefing sections", () => {
    const router = createMemoryRouter(
      [
        {
          path: "/",
          element: createElement(ExecutiveDashboard, {
            dashboard,
            onOpenRecommendation: () => undefined,
          }),
        },
      ],
      { initialEntries: ["/"] },
    );

    const html = renderToString(createElement(RouterProvider, { router }));

    expect(html).toContain("Executive Dashboard");
    expect(html).toContain("Increase inventory for Protein Powder");
    expect(html).toContain("Merchant Tasks");
    expect(html).toContain("Store Audit");
    expect(html).toContain("Audit History");
  });
});
